### PR TITLE
Feature - Update readme on tag

### LINKED ISSUE #21: Write updated version from package.json to README

### PR DESCRIPTION
**Pull request by SimoTod**
Closes #21

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
One of those things we have to test by tagging, right?

The command runs fine on my terminal though:
Screen Shot 2020-10-01 at 5 26 46 PM

```sh
echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
```
This is from existing code but what does the `:10` do here?

**Comment by ryangjchandler** [comment]
You could use [`act`](https://github.com/nektos/act) to run the action locally, but I guess that would still try to publish the release.

**Comment by SimoTod** [comment]
I tested it on a separate branch. I hardcoded the release variable and removed the npm step. Readme updated correctly

**Comment by SimoTod** [comment]
> This is from existing code but what does the `:10` do here?

@KevinBatdorf it gets the substring from the 10th character.
$GITHUB_REF contains the git reference of the branch or tag. In our case is something like `refs/tags/v1.2.3`

I've updated the PR to remove the v since we don't want it in the CDN link and it will get duplicated when you run it the second time

**Review by KevinBatdorf — APPROVED** [review]
Looks good to me. 

Side note, I've spend the past 10 hours working with GitHub actions and thankfully was able to pull some ideas from the workflows here. whew

**Comment by KevinBatdorf** [comment]
> You could use [`act`](https://github.com/nektos/act) to run the action locally, but I guess that would still try to publish the release.

@ryangjchandler Have you set this up before? I was looking at it last night. Might try setting it up over the weekend.

**Comment by ryangjchandler** [comment]
> > You could use [`act`](https://github.com/nektos/act) to run the action locally, but I guess that would still try to publish the release.
> 
> 
> 
> @ryangjchandler Have you set this up before? I was looking at it last night. Might try setting it up over the weekend.

Yeah, we all use it at work for testing CI/CD stuff & manually running CI locally.

**Review by HugoDF — APPROVED** [review]

**Pull request merged**
