### PR TITLE
Component bug with function calls

### LINKED ISSUE #74: $component / $parent should have access to Alpine magic properties
Ideally a $component should behave the same as the Alpine function and have access to magic properties such as $refs and $el.

Here is a simple example that shows this in action:
https://codepen.io/atomgiant/pen/abBOdap

A simple workaround that I am using instead of $component for now is:

`document.getElementById(e).__x.$data`

This seems to support all the standard Alpine behavior.

### PR DESCRIPTION
**Pull request by SimoTod**
Fixes #74

### CODE REVIEW

**Review by HugoDF — DISMISSED** [review]

**Comment by KevinBatdorf** [comment]
You think we could get `$component('id').$el` working? I'll try a few things but I'm guessing not.

**Comment by SimoTod** [comment]
Possibly, it might work already, to be fair. magic properties are defined on $data. Have you tried? @KevinBatdorf

**Comment by SimoTod** [comment]
@KevinBatdorf Done 🎁

**Comment by KevinBatdorf** [comment]
Works well! `$parent.$el` works too. I also tested it with `$refresh($parent.$el)` and works as well too.

One thing, your note cut off at the end. Do you think we should add a console warning for that case, or is it something that we can't really detect?

**Comment by SimoTod** [comment]
Haha, i haven't press save i think. I've already closed my laptop now, feel free to update it. Basically if you use it in x-text and the other component hasn't started, you can't access x-data.
The warning could be more custom, i suppose. Feel free to update note and warning message.
P.s. I think you can also use `$parent.$parent.foo` now

**Comment by KevinBatdorf** [comment]
`$parent.$parent` does indeed work! That's definitely worth a Tweet 😎 

I'm thinking maybe let's leave the console warning message off for now and update it depending on feedback from users.

I'll clean up the comment and merge this in, and make a release tomorrow.

**Comment by KevinBatdorf** [comment]
I understand the limitations now. I can't think of a way to get that working unless we could postpone the render until every component is initialized. That could be an idea for another helper though...

Can you check the small change I made?

**Comment by SimoTod** [comment]
> Can you check the small change I made?

@KevinBatdorf Yep, it looks good

I've added another small change to avoid an unnecessary warning. 
If we tweet about $parent.$parent we need to be clear. I'm sure people won't understand why `x-text="$parent.foo"` works, `@click="$parent.$parent.foo = 'baz'"` works and  `x-text="$parent.$parent.foo"` doesn't.
I'll think about that to see if we can improve it further.

**Comment by SimoTod** [comment]
I'm actually tempted to take it out. It's too weird that it works only in one direction. Do we really need it for refresh?

**Comment by KevinBatdorf** [comment]
I would think having `$component().$data` would make sense, and refresh would be helpful I think too (maybe `$undo` would benefit? Haven't tried).

It's been on my mind today too though since it is weird having it one way. We could just not document it though.

**Comment by SimoTod** [comment]
Yeah, refresh is good but I'm not sure if we need $component('...').$el for that helper just now. I wish Alpine would finish initialising the parent before parsing the children. :(

**Comment by KevinBatdorf** [comment]
I think we remove it then, since it can be done manually anyway if users
want that functionality. I think even returning it in a method would work,
ie

`getEl() { return this.$el }`

**Comment by SimoTod** [comment]
I've removed it. It wasn't part of the bug anyway. Maybe we can explore it on a different PR.

**Pull request merged**
