### PR TITLE
$interval not clearing timeout

### PR DESCRIPTION
**Pull request by SimoTod**
Note, I updated the tests initially because fakeTimers and waitFor don't seem to play fairly with each other (Tests were passing even with different wrong expectations because waitFor uses setTimeout too).

First commit is to show the test are still passing without fake timers
Second commit introduces the failing test
Third and forth commit are just to bring it up to date with master (still failing)
Fifth commit is the fix

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
I'll look at this (and everything else) tomorrow, quite possibly on some sort of live stream (just for fun) if you want to hang out

**Comment by SimoTod** [comment]
What time?

**Comment by KevinBatdorf** [comment]
I'll try to get on early afternoon USA Eastern time.

**Comment by ryangjchandler** [comment]
> I'll try to get on early afternoon USA Eastern time.

Put a link on Twitter, I'll tune in!

**Review by KevinBatdorf — APPROVED** [review]
This looks good! Thank you!

**Pull request merged**
