### PR TITLE
Feature/magic properties in component

### PR DESCRIPTION
**Pull request by SimoTod**
Does exactly what it says on the tin. ;)
The price to pay is that, for both parent and component, if the observed component is not ready, we wait a few ms.

Tested chrome, firefox, safari, and Edge. I still need to test IE but I'm optimistic.

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
This is great! Is this how it works?

If a component isn't ready, return a proxy, that if accessed will return an empty string. Then on the next frame, try again, and again, etc until `component.__x` is available, in which case we return the component as usual.

Could we write a reliable unit test for `getNoopProxy()`? 

When specifically does `typeof key === 'symbol'` ?

**Comment by KevinBatdorf** [comment]
Just messing around a bit with this and thought of another useful abstraction, so we can use this in other helpers as needed:

```js
Alpine.addMagicProperty('parent', ($el) => {
    if (typeof $el.$parent !== 'undefined') return $el.$parent

    const parentComponent = $el.parentNode.closest('[x-data]')
    if (!parentComponent) throw new Error('Parent component not found')

    return waitUntilReady(parentComponent, $el, () => {
        $el.$parent = syncWithObservedComponent(componentData(parentComponent), parentComponent, objectSetDeep)

        updateOnMutation(parentComponent, () => {
            $el.$parent = syncWithObservedComponent(parentComponent.__x.getUnobservedData(), parentComponent, objectSetDeep)
            $el.__x.updateElements($el)
        })
        return $el.$parent
    })
})
```
then in utils:
```js
// Continuously check the observed component until it's ready.
export function waitUntilReady(componentBeingObserved, component, callback) {
    if (!componentBeingObserved.__x) {
        window.requestAnimationFrame(() => component.__x.updateElements(component))
        return getNoopProxy()
    }
    return callback()
}
```

Then the same for $component

You think that's an improvement?

**Comment by SimoTod** [comment]
> This is great! Is this how it works?
> 
> If a component isn't ready, return a proxy, that if accessed will return an empty string. Then on the next frame, try again, and again, etc until `component.__x` is available, in which case we return the component as usual.
> 
> Could we write a reliable unit test for `getNoopProxy()`? 
> 
> When specifically does `typeof key === 'symbol'` ?
> 
> 

Yep, one frame should be enough to initialise the other component so it should only retry once but theoretically it will try multiple times until the observed component is ready. 

Good shout for the test. I refactored it out in the last commit but I didn't think about the test. I'll add a test for it soon. 

So, when you try to print an object, modern browser will use a special symbol called toPrimitive (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toPrimitive) which is like a function returning a string. We could test if the call is for that special symbol but for symplicity, I specified that each symbol will return an empty string.
IE will use a different function (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf) which, being a normal function, it will resolve normally through the proxy (we are always proxing a noop operation). I think the implementation covers all the scenarios.

**Comment by SimoTod** [comment]
> Just messing around a bit with this and thought of another useful abstraction, so we can use this in other helpers as needed:
> 
> ```js
> Alpine.addMagicProperty('parent', ($el) => {
>     if (typeof $el.$parent !== 'undefined') return $el.$parent
> 
>     const parentComponent = $el.parentNode.closest('[x-data]')
>     if (!parentComponent) throw new Error('Parent component not found')
> 
>     return waitUntilReady(parentComponent, $el, () => {
>         $el.$parent = syncWithObservedComponent(componentData(parentComponent), parentComponent, objectSetDeep)
> 
>         updateOnMutation(parentComponent, () => {
>             $el.$parent = syncWithObservedComponent(parentComponent.__x.getUnobservedData(), parentComponent, objectSetDeep)
>             $el.__x.updateElements($el)
>         })
>         return $el.$parent
>     })
> })
> ```
> then in utils:
> ```js
> // Continuously check the observed component until it's ready.
> export function waitUntilReady(componentBeingObserved, component, callback) {
>     if (!componentBeingObserved.__x) {
>         window.requestAnimationFrame(() => component.__x.updateElements(component))
>         return getNoopProxy()
>     }
>     return callback()
> }
> ```
> 
> Then the same for $component
> 
> You think that's an improvement?

Yeah, we can move it as well in case we need it in the future. It adds a few bytes every time you extract a function but I don't think it's going to be a problem. 👍

**Comment by KevinBatdorf** [comment]
We wouldn't have to export the `getNoopProxy` anymore I guess so maybe it's the same?

**Comment by SimoTod** [comment]
Yeah, it's probably 10 bytes or something like that anyway. I'll make those changes later 👌

**Comment by SimoTod** [comment]
Added tests for getNoopProxy. Actually, we don't need `if (typeof key === 'symbol') return () => ''` anymore.
The first version was `return new Proxy({}, handler)` so I needed to convert the js toString to the empty string but now that we are proxying `() => ''` since that symbol is a function, it just works.

I'm still exporting getNoopProxy so I can unit test it

**Comment by KevinBatdorf** [comment]
Works great. Also `$refresh($parent.$parent.$el)` works too, which hopefully people don't do :) 

I'll merge it in now and make a Friday release?

Since $component is essentially complete now we could bump to 1.0. Might be something to do when Alpine v3 is out though

**Comment by SimoTod** [comment]
@KevinBatdorf I think we can bump to v1 now. We are unlikely to introduce breaking changes. When Alpine v3 is out, we will probably need to re-assess everything because I suspect none of the helpers will work out of the box (and it will probably be a v2).

**Comment by KevinBatdorf** [comment]
@SimoTod I wonder if we could ask Caleb to get access to v3 24 hours prior or something like that so confirm it's working. 

I'll do v1 release Friday. Need to think about how to Tweet it best to maybe get some more hype.

**Pull request merged**
